const ACTIONS_TYPES = {
    GET_CUR_TASKS: 'GET_CUR_TASKS',
    GET_COMPL_TASKS: 'GET_COMPL_TASKS',
    COMPLETE_TASK: 'COMPLETE_TASK',
    ADD_TASK: 'ADD_TASK',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    RESPONSE_401: 'RESPONSE_401',
};

module.exports = { ACTIONS_TYPES };
